# 服务配置
server:
   port: 7000
   servlet:
      context-path: /api
      
spring:
  # 读取配置文件
  profiles:
    include: redis-test,logging,exception,mysql-test,mybatis,mongo,elasticsearch,shiro,common,socket
    
