# 服务配置
server:
   port: 7000
   servlet:
      context-path: /api
      
spring:
  # 读取配置文件
  profiles:
    include: redis-prod,logging,exception,mysql-prod,mybatis,mongo,elasticsearch,shiro,common
    
