# shiro配置
shiro:
  cache:
    expire: 21600
    prefix: "lhq:superboot:shiro:cache:"
    authenticName: authenticationCache
    authorizaName: authorizationCache
  session:
    # 30天过期
    timeout: 2592000000
    idName: SHIROJSESSIONID
    # 设置session失效的扫描时间(1小时扫一次)
    valid: 3600000
    # redis在session超时时间s（这个无所谓，因为过期了会根据session失效扫描时间定时删除）
    prefix: "lhq:superboot:shiro:session:"
    expire: -1
  cookie:
    name: rememberMe
    timeout: 259200
  login:
    # 账号登录限制过期时间s(如12小时候清空账号登录次数)
    accountlockTime: 43200
    # 账号锁次数(修改账号状态)
    accountlockCount: 10
    accountlockPrefix: "lhq:superboot:shiro:login:count:"
    # 频繁锁次数(增加redis限制)
    repeatlockCount: 5
    # 频繁锁时间s
    repeatlockTime: 300
    repeatlockPrefix: "lhq:superboot:shiro:login:locked:"
  filter:
    # 授权地址
    authUrl: /**