spring:
  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password: invest9527
    timeout: 10000
    jedis:
       pool:
          max-active: 8
          max-wait: -1
          max-idle: 3
          min-idle: 0