spring:
  # redis配置
  redis:
    # host: 127.0.0.1
    host: 39.98.184.99
    port: 6379
    password: 123456
    timeout: 10000
    jedis:
       pool:
          max-active: 8
          max-wait: -1
          max-idle: 3
          min-idle: 0