spring:
  # redis配置
  redis:
    host: 106.54.199.36
    port: 6379
    password: sullaylhq
    timeout: 10000
    jedis:
       pool:
          max-active: 8
          max-wait: -1
          max-idle: 3
          min-idle: 0