# mysql配置信息
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_boot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: '@YiMi9527'
    driver-class-name: com.mysql.cj.jdbc.Driver