# mysql配置信息
spring:
  datasource:
    url: jdbc:mysql://cdb-6rbyqvpq.bj.tencentcdb.com:10108/sullay_blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: yangjinwei0201
    driver-class-name: com.mysql.cj.jdbc.Driver